[package]
name = "fish_n_chip"
version = "0.1.0"
authors = ["Arthur 'Riz' Cros <arthur.cros@etna.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
sdl2 = "0.34.0"
clap = "2.33.1"
